### ISSUE TITLE
Potentially store ScriptExtension as a set of bitfields

### ISSUE THREAD

**Issue by Manishearth** [unicode-rs/unicode-script#2]
We can assign each `Script` value to a bit and store `ScriptExtension` as a bitfield made of three `u64`s. Intersection becomes fast, and we can use popcnt to find if something is single script. We can export constants for each script value to make this easy to use.

cc @crlf0710

**Comment by Manishearth** [comment]
Unknown would be the zero state, Common would be the all-set state, Inherited would be Common with an additional Inherited bit set.

**Comment by Manishearth** [comment]
To make things even faster we could  store the script extension value in the `SCRIPTS` table as well.

**Comment by crlf0710** [comment]
Seems a good idea.
